module.exports = {
	"props-title": "Properties for $1",
	"props-buttons-close": "Close",

	"props-basic": "Basic",
	"props-basic-name": "Name:",
	"props-basic-type": "Type:",
	"props-basic-size": "Size:",
	"props-basic-location": "Location:",
	"props-basic-atime": "Last access time:",
	"props-basic-mtime": "Last modification time:",

	"props-perms": "Permissions",
	"props-perms-owner": "Owner:",
	"props-perms-owner-data": "$1 ($2)",
	"props-perms-group": "Group:",
	"props-perms-others": "Others",
	"props-perms-access": "Access:",
	"props-perms-access-rw": "Read and write",
	"props-perms-access-r": "Read-only",
	"props-perms-access-w": "Write-only",
	"props-perms-access-none": "None",
	"props-perms-exec": "Execute:",
	"props-perms-exec-box": "Allow execution of file as program",

	"props-openwith": "Open with",
	"props-openwith-title": "Choose a program to open \"$1\" and other files of type $2.",
	"props-openwith-programs": "Programs that can open this file",
	"props-openwith-others": "All programs",
};